### ISSUE TITLE
How can i install depends to my host?

### ISSUE THREAD

**Issue by MatroskinGG** [python-pillow/pillow-depends#38]
I tried to install libjpeg or libwebp or zlib files to my host for discord bot a lot of times with different ways, but it didnt work. When i tried to just download Pillow with pip, it said that cant find jpeg files. Then i found way to disable jpeg, but as i understood, it disables all libraries, because when i try to open different file types with `Image.open()`, It always crashes with error "Cant indificate file ...". I get my image from url, so can i can do without `Image.open()`? Or there are file type that dont need library? If there arent any way, so how can i install depended libraries to host? I am pretty new to this, and may be i cant understand simple things, but i really need help with this

**Comment by radarhere** [comment]
Hi. I think the better place for this is at https://github.com/python-pillow/Pillow. Please open a new issue there.
I wouldn't try disabling jpeg.
What operating system are you using? How are you trying to install libjpeg?

**Comment by radarhere** [comment]
Replaced by https://github.com/python-pillow/Pillow/issues/5428
